version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - mongo
    volumes:
      - ./src:/src
      - ./test:/test
    entrypoint:
      - lein
      - run
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
