version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - redis
    volumes:
      - ./src:/src
      - ./test:/test
    entrypoint:
      - lein
      - run
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"